#!/bin/bash
set -euxo pipefail

[[ "$USER" != "yasuhisa" ]] && echo "You may not want to use this script." > /dev/stderr && exit 1

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/syou6162/setup/master/brew)"

trap 'rm -rf /tmp/setup' EXIT SIGHUP SIGINT SIGQUIT SIGTERM
git clone https://github.com/syou6162/setup /tmp/setup
/tmp/setup/setup
