#!/bin/bash
set -euxo pipefail

brew update

formulas=( \
  jq \
  wget \
  curl \
  git \
  tig \
  zsh \
  vim \
  peco \
  fish \
  nkf \
  watch \
  go \
  direnv \
  rbenv \
  nodenv \
  pyenv \
  tfenv \
  awslogs \
  helm \
  argo \
  coreutils \
)

for formula in "${formulas[@]}"; do
  tools/brew-install "$formula"
done
