#!/bin/bash
set -euxo pipefail

brew update

formulas=( \
  coreutils \
  wget \
  curl \
  git \
  tig \
  jq \
  zsh \
  vim \
  tmux \
  peco \
  fish \
  sshuttle \
  awscli \
  terraform \
  redis \
  nkf \
  watch \
  go \
  direnv \
  scala sbt \
  rbenv \
  nodenv \
  pyenv \
  ansible \
  mecab \
  vegeta \
  awslogs \
  reattach-to-user-namespace \
  mackerelio/mackerel-agent/mackerel-agent \
  mackerelio/mackerel-agent/mkr \
  silinternational/tap/ecs-deploy \
  itchyny/tap/base58 \
  goreleaser/tap/goreleaser \
  kayac/tap/ecspresso \
)

for formula in "${formulas[@]}"; do
  tools/brew-install "$formula"
done
