#!/bin/bash
set -euxo pipefail

formulas=( \
  docker \
  java \
  iterm2 \
  google-chrome \
  slack \
  hammerspoon \
  visual-studio-code \
  dropbox \
  1password \
)

for formula in "${formulas[@]}"; do
  tools/brew-cask-install "$formula"
done
