#!/bin/bash
set -euxo pipefail

formulas=( \
  docker \
  google-chrome \
  slack \
  hammerspoon \
  visual-studio-code \
  1password \
  aquaskk \
  alfred \
  karabiner-elements \
  google-cloud-sdk \
)

for formula in "${formulas[@]}"; do
  tools/brew-cask-install "$formula"
done
