#!/bin/bash
set -euxo pipefail

target=~/.files

tools/git-clone https://github.com/syou6162/config "$target"

# $HOME以下に設定ファイル群へのシンボリックリンクを貼る
for filename in .zshrc .zshenv .gitconfig .gitexclude .tmux.conf .vimrc .tigrc .ctags .tern-project; do
  tools/make-symlink "$target/$filename" ~/"$filename"
done

tools/make-symlink "${target}/config.fish" $HOME/.config/fish/config.fish
tools/make-symlink "${target}/fishfile" $HOME/.config/fish/fishfile

tools/make-symlink "${target}/init.lua" $HOME/.hammerspoon/init.lua

tools/make-symlink "${target}/karabiner.json" $HOME/.config/karabiner/karabiner.json
