#!/bin/bash
set -euxo pipefail

extensions=( \
  golang.go \
  ms-python.python \
  ms-vscode-remote.remote-containers \
  rebornix.ruby \
  vscodevim.vim \
  wingrunr21.vscode-ruby \
  github.copilot \
  github.copilot-chat \
  github.vscode-github-actions \
  bierner.markdown-mermaid \
  dart-code.dart-code \
  dart-code.flutter \
  hashicorp.terraform \
  innoverio.vscode-dbt-power-user \
  vsls-contrib.codetour \
)

for extension in "${extensions[@]}"; do
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" --install-extension "${extension}"
done
