#!/bin/bash
set -euxo pipefail


cmdname="$(basename "${BASH_SOURCE[0]}")"

if ! command -v defaults >/dev/null; then
  echo "$cmdname: defaults not found" >&2
  exit
fi

if ! command -v osascript >/dev/null; then
  echo "$cmdname: osascript not found" >&2
  exit
fi

# Ref: https://github.com/mathiasbynens/dotfiles/blob/master/.macos

# Kill System Preferences to prevent them from overriding settings
osascript -e 'tell application "System Preferences" to quit'

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Mute the beep sound
defaults write NSGlobalDomain com.apple.sound.beep.volume -int 0

# Dock
defaults write com.apple.dock orientation -string "right"

osascript -e 'tell application "Dock" to quit'

# Screenshot
defaults write com.apple.screencapture type png
defaults write com.apple.screencapture disable-shadow -bool true
mkdir -p ~/Desktop/screenshots
defaults write com.apple.screencapture location ~/Desktop/screenshots

# Key
defaults write NSGlobalDomain InitialKeyRepeat -int 25
defaults write NSGlobalDomain KeyRepeat -int 2

# キーボード => ショートカット => アプリケーション
# 「ウインドウを画面左側に移動」をCtrl + Cmd + 左矢印キー
defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "\U30a6\U30a4\U30f3\U30c9\U30a6\U3092\U753b\U9762\U53f3\U5074\U306b\U79fb\U52d5" "@^\U2192"
# 「ウインドウを画面右側に移動」をCtrl + Cmd + 右矢印キー
defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "\U30a6\U30a4\U30f3\U30c9\U30a6\U3092\U753b\U9762\U5de6\U5074\U306b\U79fb\U52d5" "@^\U2190"
# 「ズーム」をCtrl + Cmd + 上矢印キー
defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "\U30ba\U30fc\U30e0" "@^\U2191"

# ステッキーズのスタイル付きのペーストをスタイルなしにする
defaults write com.apple.Stickies NSUserKeyEquivalents -dict-add "\U30da\U30fc\U30b9\U30c8\U3057\U3066\U30b9\U30bf\U30a4\U30eb\U3092\U5408\U308f\U305b\U308b" "@v"

# 拡張子を常に表示
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# バッテリー残量を%表記に
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# 隠しファイルや隠しフォルダを表示
defaults write com.apple.finder AppleShowAllFiles -bool true

# Remap keys (ref: https://developer.apple.com/library/archive/technotes/tn2450/_index.html)
keyboardid=$(ioreg -c AppleEmbeddedKeyboard -r | grep -Eiw "VendorID|ProductID" | awk '{ print $4 }' | tr '\n' '-' && echo 0) || :
if [[ -n "$keyboardid" ]]; then
  # Caps Lock 0x39 -> Left Control 0xe0
  defaults -currentHost write -g "com.apple.keyboard.modifiermapping.$keyboardid" -array \
    '<dict>
      <key>HIDKeyboardModifierMappingSrc</key> <integer>0x700000039</integer>
      <key>HIDKeyboardModifierMappingDst</key> <integer>0x7000000e0</integer>
    </dict>'
fi
