#!/bin/bash
set -euxo pipefail

cd "$(dirname "$0")"

# shellcheck disable=SC2015
test -t 0 && sudo -v || :

./dotfiles
./macos

./brew
./brew-formula
./brew-cask-formula

./install-vscode-extensions
