name: bashスクリプトのフォーマットをチェック

on: [push]

jobs:
  check_bash_scripts_format:
    name: Check format of bash scripts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - run: find script -type f -name '*' | xargs -I% grep -l "^#!/bin/bash" % | xargs -I% shellcheck -e SC2002,SC2011,SC2013,SC2016,SC2038,SC2164 %
