name: bashスクリプトのフォーマットをチェック

on: [push]

jobs:
  check_bash_scripts_format:
    name: Check format of bash scripts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - run: find script -type f -name '*' | xargs -I% grep -l "^#!/bin/bash" % | xargs -I% shellcheck -e SC2002,SC2011,SC2013,SC2016,SC2038,SC2164 %
