name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Delete Python executable symlinks
      run: find /usr/local/bin -lname '*/Python.framework/*' -print -delete      
    - name: Uninstall pre-installed packages
      run: brew list | xargs brew uninstall --force
    - name: Test setup scripts
      run: ./setup
