name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Uninstall default go
      run: brew uninstall go@1.15
    - name: Test setup scripts
      run: ./setup
