name: Daily Schedule

on:
  schedule:
    # 毎日 09:00 JST
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Delete Python executable symlinks
      run: find /usr/local/bin -lname '*/Python.framework/*' -print -delete      
    - name: Uninstall pre-installed packages
      run: brew list | xargs brew uninstall --force
    - name: Test setup scripts
      run: ./setup
